name: hello-world
on: pull_request
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
        echo "Hello World!"
        echo github.head_ref: ${{ github.head_ref }}
